### PR TITLE
Ehance MC page and Fix #49

### LINKED ISSUE #49: [Bug]:
### What happened?

The new functionality for the Minecraft page is great, but the full screen map presents a UX problem. On both my 15" laptop and standard sized iphone14 you can scroll down to the map and effectively be stuck at that point. Stuck meaning the map has taken up the entire screen and thus all swiping/scrolling only works on the map and the rest of the site can no longer be accessed.

### If you expected something else to occur what did you expect?

I expect to be able to navigate as normal.

### What operating system are you using?

Windows 11 with 15 screen and iOS with standard screen size.

### What browsers are you seeing the problem on?

Firefox, Chrome, DuckDuckGo, Edge

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by TheDarkThief**
MINOR CHANGES

Tweaked the gradient backgrounds and doing a slight spruce up around the embedded squaremap

fixes #49
By adding margins around the map

### CODE REVIEW

**Comment by jaredscarr** [comment]
@TheDarkThief @uellenberg are we still doing the beta branch workflow? If so this should be a PR into beta right?

**Comment by TheDarkThief** [comment]
I don't know, I think it would be ideal if it went to beta, but considering this is just a minor change and small issue fix, might as well merge to main ¯\\\_(ツ)\_/¯

**Comment by jaredscarr** [comment]
If you can rebase the PR to beta it would be better. Otherwise beta and main are out of sink and we would have to rebase that branch.

**Comment by TheDarkThief** [comment]
ehhhhhhh it's a minor cahgne, just let it slide. . . please me no want to work more
image

**Comment by TheDarkThief** [comment]
fine give me a minute

**Pull request closed without merging**
